name: Run Python Scripts

on:
  schedule:
    # Runs github.auto.py at 9:00, 12:00, 18:00, and 21:00 UTC every day
    - cron: "0 9,12,18,21 * * *"
    # Runs github.auto.reply.py at 8:00, 13:00, and 19:30 UTC every day
    - cron: "0 8,13 * * *"
    - cron: "30 19 * * *"

jobs:
  run-github-auto:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # Replace with the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run github.auto.py
        if: github.event.schedule == '0 9 * * *' || github.event.schedule == '0 12 * * *' || github.event.schedule == '0 18 * * *' || github.event.schedule == '0 21 * * *'
        run: |
          python github.auto.py
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}

  run-github-auto-reply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # Same Python version for consistency

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run github.auto.reply.py
        if: github.event.schedule == '0 8 * * *' || github.event.schedule == '0 13 * * *' || github.event.schedule == '30 19 * * *'
        run: |
          python github.auto.reply.py
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
