name: Run Python Script

on:
  schedule:
    # Runs at 9:00, 12:00, 18:00, and 21:00 UTC every day
    - cron: "0 9,12,18,21 * * *"

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x" # Use the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have a requirements.txt if needed

      - name: Run the python script
        run: |
          python github.auto.py  # Your script
